from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

ROOT = Path(__file__).resolve().parent.parent
EXPECTED_TABLES = {
    "entities", "entity_aliases", "runs", "score_snapshots", "trend_snapshots", "alerts",
}


def _cfg(db_url: str) -> Config:
    cfg = Config(str(ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(ROOT / "migrations"))
    cfg.set_main_option("sqlalchemy.url", db_url)
    return cfg


@pytest.fixture()
def db_url(tmp_path, monkeypatch):
    url = f"sqlite:///{tmp_path}/migrate.db"
    # env.py reads DATABASE_URL; pin it so the test targets the temp DB.
    monkeypatch.setenv("DATABASE_URL", url)
    return url


def test_upgrade_creates_full_schema(db_url):
    command.upgrade(_cfg(db_url), "head")
    tables = set(inspect(create_engine(db_url)).get_table_names())
    assert EXPECTED_TABLES <= tables
    assert "alembic_version" in tables


def test_migration_is_in_sync_with_models(db_url):
    # After upgrading, autogenerate must detect no differences vs the ORM models.
    cfg = _cfg(db_url)
    command.upgrade(cfg, "head")
    command.check(cfg)  # raises AutogenerateDiffsDetected if the migration drifts


def test_downgrade_then_upgrade_roundtrip(db_url):
    cfg = _cfg(db_url)
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    tables = set(inspect(create_engine(db_url)).get_table_names())
    assert not (EXPECTED_TABLES & tables)  # all dropped
    command.upgrade(cfg, "head")
    tables = set(inspect(create_engine(db_url)).get_table_names())
    assert EXPECTED_TABLES <= tables
