"""initial schema

Revision ID: 40ddcb148a10
Revises: 
Create Date: 2026-06-13 15:49:27.290975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ddcb148a10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('entities_tracked', sa.Integer(), nullable=False),
    sa.Column('new_entities_found', sa.Integer(), nullable=False),
    sa.Column('report_md_path', sa.String(length=512), nullable=True),
    sa.Column('report_json_path', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_normalized', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('tier', sa.String(length=32), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('last_event_date', sa.Date(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_name_normalized'), ['name_normalized'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('old_value', sa.String(length=64), nullable=True),
    sa.Column('new_value', sa.String(length=64), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('webhook_delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('alias_normalized', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalized')
    )
    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'entity_id', name='uq_snapshot_run_entity')
    )
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=True),
    sa.Column('rank_delta', sa.Integer(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'entity_id', name='uq_trend_run_entity')
    )
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_snapshots_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trend_snapshots_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_run_id'))
        batch_op.drop_index(batch_op.f('ix_trend_snapshots_entity_id'))

    op.drop_table('trend_snapshots')
    op.drop_table('score_snapshots')
    op.drop_table('entity_aliases')
    op.drop_table('alerts')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_name_normalized'))

    op.drop_table('entities')
    op.drop_table('runs')
    # ### end Alembic commands ###
